name: deploy nastya

on:
  push:
    branches: [ 'master' ]

  pull_request:
    branches: [ 'master' ]

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Prepare
        shell: sh
        run: |
          apk update
          apk add nodejs docker-cli docker-cli-buildx

      - name: Checkout repository
        uses: https://github.com/actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          file: Dockerfile
          push: true
          tags: vistee/pprfnk:nastya
