name: Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop nastya bot
        run: systemctl stop nasty && kill -s 9 $(pidof /home/nastya/bin/python)
      - name: Pull nastya source
        run: cd /opt/nastya && git pull
      - name: Start nastya bot
        run: systemctl start nasty