name: Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Stop nasty
        run: systemctl stop nasty && kill -s 9 $(pidof /home/nastya/bin/python)
      - name: Start nasty
        run: systemctl start nasty