name: Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Stop Nastya bot
        run: systemctl stop nastya
      - name: Pull Nastya source
        run: cd /opt/nastya && rm tools/config.json artint/params.json core/params.json && cp ../nastya_params.json artint/params.json && cp ../nastya_params.json core/params.json && cp ../nastya.json  tools/config.json && git pull
      - name: Start Nastya  bot
        run: systemctl start nastya
